version: '3.1'

services:
  php:
    container_name: jasper-container
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 6000:80
    volumes:
      - ./app:/var/www/html/